#ifndef PARAMETERS_H
#define PARAMETERS_H

#include "_parameters.h"

#define TWEAKEY_LENGTH_BITS       (TWEAK_LENGTH_BITS+KEY_LENGTH_BITS)
#define ROUND_TWEAKEY_LENGTH_BITS 64
#define BLOCK_LENGTH_BITS         128
#define NONCE_LENGTH_BITS         120
#define TAG_LENGTH_BITS           128

#define TWEAK_BYTES         (TWEAK_LENGTH_BITS/8)
#define KEY_BYTES           (KEY_LENGTH_BITS/8)
#define TWEAKEY_BYTES       (TWEAKEY_LENGTH_BITS/8)
#define ROUND_TWEAKEY_BYTES (ROUND_TWEAKEY_LENGTH_BITS/8)
#define BLOCK_BYTES         (BLOCK_LENGTH_BITS/8)
#define NONCE_BYTES         (NONCE_LENGTH_BITS/8)
#define TAG_BYTES           (TAG_LENGTH_BITS/8)

#endif /* PARAMETERS_H */
