#!/bin/bash

set -eux

scripts_dir=$(realpath $(dirname $0))
felics_parent_dir=${scripts_dir}/../../

generate-version ()
{
    PYTHONPATH="${scripts_dir}" python3 -m felics.version
}

(
    cd ${felics_parent_dir}

    output=FELICS-AE/results/FELICS-AE.tar

    git archive -o ${output} HEAD FELICS-AE
    generate-version > FELICS-AE/VERSION

    tar uf ${output} FELICS-AE/VERSION
    gzip -f ${output}
)
