#!/bin/bash

set -eux

scripts_dir=$(realpath $(dirname $0))
felics_parent_dir=${scripts_dir}/../../

if (($# < 1))
then
    output_dir=$(realpath ${felics_parent_dir}/FELICS-AE/results)
else
    output_dir=$(realpath $1)
fi

(
    cd ${felics_parent_dir}

    output=${output_dir}/FELICS-AE.tar

    git archive -o ${output} HEAD FELICS-AE
    ${scripts_dir}/version.sh > FELICS-AE/VERSION

    tar uf ${output} FELICS-AE/VERSION
    gzip -f ${output}
)
