#ifndef PARAMETERS_H

#define PARAMETERS_H
#define KEY_SIZE 32
#define ROUND_KEYS_SIZE 0
#define CRYPTO_NSECBYTES 0
#define CRYPTO_NPUBBYTES 8
#define CRYPTO_ABYTES 16

#define TWEAKEY_STATE_SIZE 384

#endif /* PARAMETERS_H */
