#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2019 Airbus Cybersecurity SAS

set -eux

scripts_dir=$(realpath $(dirname $0))
root_dir=$(git rev-parse --show-toplevel)

if (($# < 1))
then
    output_dir=$(realpath ${root_dir}/results)
else
    output_dir=$(realpath $1)
fi

(
    cd ${root_dir}

    output=${output_dir}/FELICS-AE.tar

    git archive --prefix=FELICS-AE/ -o ${output} HEAD .
    ${scripts_dir}/version.sh > VERSION

    tar uf ${output} --transform 's,^,FELICS-AE/,' VERSION
    gzip -f ${output}
)
