#!/usr/bin/env python3

from argparse import ArgumentParser, ArgumentTypeError
from datetime import datetime
from os import path
from subprocess import run
from sys import argv

from felics import version


_SCRIPTS_DIR = path.dirname(path.realpath(argv[0]))
_ROOT_DIR = path.join(_SCRIPTS_DIR, path.pardir)
_CIPHERS_DIR = path.join(_ROOT_DIR, 'source', 'ciphers')
_RESULTS_DIR = path.join(_ROOT_DIR, 'results')

_ARCHITECTURES = 'AVR MSP ARM PC NRF52840 STM32L053'


def _default_output_filename():
    date = datetime.now().strftime('%Y.%m.%d-%H.%M.%S')
    branch = version.branch()

    if branch is None:
        return '{d}.json'.format(d=date)

    return '{d}-{b}.json'.format(d=date, b=branch.replace('/', '-'))


def _validate_architectures(argument):
    allowed = set(_ARCHITECTURES.split())
    requested = set(argument.split())

    unknown = requested-allowed
    if unknown:
        raise ArgumentTypeError('Unknown architectures: '+', '.join(unknown))

    return argument


def _parse_arguments():
    parser = ArgumentParser()
    parser.add_argument(
        'ciphers', nargs='+',
        help='List of cipher folders in source/ciphers; globs are supported.'
    )
    parser.add_argument(
        '-a', '--architectures', default=_ARCHITECTURES,
        type=_validate_architectures,
        help='Space-separated list of platforms; default: "{a}"'.format(a=_ARCHITECTURES)
    )
    parser.add_argument(
        '--options', default='-O3',
        help='Semicolon-separated list of compiler options; default: "-O3"'
    )

    default_output = _default_output_filename()
    parser.add_argument(
        '-o', '--output',
        default=default_output,
        help='default: {o}'.format(
            o=path.relpath(path.join(_RESULTS_DIR, default_output), _ROOT_DIR)
        )
    )

    return parser.parse_args()


def _run_felics(ciphers, architectures, compiler_options, output):
    command = (
        path.join(_SCRIPTS_DIR, 'collect_ciphers_metrics.sh'),
        '-c='+' '.join(ciphers),
        '-a='+architectures,
        '-co='+compiler_options,
        '-j='+output
    )

    run(command, check=True)


def _show_results(output):
    command = (path.join(_SCRIPTS_DIR, 'felics-publish'),
               path.join(_RESULTS_DIR, output))

    run(command, check=True)


if __name__ == '__main__':
    args = _parse_arguments()

    _run_felics(args.ciphers, args.architectures, args.options, args.output)
    _show_results(args.output)
