#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2019 Airbus Cybersecurity SAS

from argparse import ArgumentParser, ArgumentTypeError
from datetime import datetime
from os import path
from subprocess import run
from sys import argv

from felics import ARCHITECTURES, ARCHITECTURES_BY_NAME, version


_SCRIPTS_DIR = path.dirname(path.realpath(argv[0]))
_ROOT_DIR = path.join(_SCRIPTS_DIR, path.pardir)
_CIPHERS_DIR = path.join(_ROOT_DIR, 'source', 'ciphers')
_RESULTS_DIR = path.join(_ROOT_DIR, 'results')


def _default_output_filename():
    date = datetime.now().strftime('%Y.%m.%d-%H.%M.%S')
    branch = version.branch()

    if branch is None:
        return '{d}.json'.format(d=date)

    return '{d}-{b}.json'.format(d=date, b=branch.replace('/', '-'))


def _validate_architectures(argument):
    requested = tuple(ARCHITECTURES_BY_NAME[a] for a in argument.split())

    unknown = set(requested)-set(ARCHITECTURES)
    if unknown:
        raise ArgumentTypeError('Unknown architectures: '+', '.join(sorted(unknown)))

    return requested


def _parse_arguments():
    parser = ArgumentParser()
    parser.add_argument(
        'ciphers', nargs='+',
        help='List of cipher folders in source/ciphers; globs are supported.'
    )

    parser.add_argument(
        '-a', '--architectures', default=ARCHITECTURES,
        type=_validate_architectures,
        help='Space-separated list of platforms; default: "{a}"'.format(
            a=' '.join(ARCHITECTURES_BY_NAME.keys())
        )
    )

    parser.add_argument(
        '--options', default='-O3',
        help='Semicolon-separated list of compiler options; default: "-O3"'
    )

    default_output = _default_output_filename()
    parser.add_argument(
        '-o', '--output',
        default=default_output,
        help='default: {o}'.format(
            o=path.relpath(path.join(_RESULTS_DIR, default_output), _ROOT_DIR)
        )
    )

    return parser.parse_args()


def _run_felics(ciphers, architectures, compiler_options, output):
    command = (
        path.join(_SCRIPTS_DIR, 'plumbing', 'collect_ciphers_metrics.sh'),
        '-c='+' '.join(ciphers),
        '-a='+' '.join(a.codename for a in architectures),
        '-co='+compiler_options,
        '-j='+output
    )

    run(command, check=True)


def _show_results(output):
    command = (path.join(_SCRIPTS_DIR, 'felics-publish'),
               path.join(_RESULTS_DIR, output))

    run(command, check=True)


if __name__ == '__main__':
    args = _parse_arguments()

    _run_felics(args.ciphers, args.architectures, args.options, args.output)
    _show_results(args.output)
