#!/bin/bash

set -eux

auth_root=$(git rev-parse --show-toplevel)/authenticated_block_ciphers
ciphers_root=${auth_root}/source/ciphers
scripts_dir=${auth_root}/scripts
results_dir=${auth_root}/results

scenario=1

if [ $# -lt 2 ]
then
    ciphers=($(pwd | sed -r 's,.+/([^/]+)/source$,\1,'))
else
    ciphers=($(cd ${ciphers_root} ; echo $2))
fi

if [ $# -lt 3 ]
then
    branch=$(git symbolic-ref --short HEAD || git show --no-patch --format=format:%h)
    output="$(date +%Y.%m.%d-%H.%M.%S)-${branch}.json"
else
    output="$3"
fi


for c in ${ciphers[@]}
do
    (
        cd ${ciphers_root}/${c}/source
        make cleanall
        make cipher
        make test-cipher
    )
done


. ${scripts_dir}/constants/constants.sh

restore-cpu ()
{
    sudo cpufreq-set -c ${PC_EXECUTION_TIME_CPU} -g powersave
}

trap restore-cpu ERR

sudo cpufreq-set -c ${PC_EXECUTION_TIME_CPU} -g performance
${scripts_dir}/collect_ciphers_metrics.sh "-c=${ciphers[*]}" "-a=$1" -s=$scenario -co=-O3 -j="${output}"

restore-cpu

felics-publish "${results_dir}/${output}"
